version: '3.8'

services:
  # Инфраструктурные сервисы
  postgres-discovery:
    image: postgres:17
    environment:
      POSTGRES_DB: eureka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - pgdata-discovery:/var/lib/postgresql/data
    networks:
      - bank-network

  postgres-config:
    image: postgres:17
    environment:
      POSTGRES_DB: config
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata-config:/var/lib/postgresql/data
    networks:
      - bank-network

  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-discovery
    networks:
      - bank-network

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-config
    networks:
      - bank-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - service-discovery
      - config-server
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  pgdata-discovery:
  pgdata-config: